package ntlmssp

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// Interop fixtures generated by an independent implementation (impacket 0.12.0):
// a CHALLENGE built with this package's exact layout (BuildChallenge) fed to
// impacket getNTLMSSPType3 for user "alice", domain "WORKGROUP", password
// "S3cret!", with server challenge 0123456789abcdef.
const (
	fixtureChallengeHex = "0123456789abcdef"
	fixtureNTHashHex    = "10b2f1961375b20126508c2267862bf0" // impacket compute_nthash("S3cret!")
	fixtureType2Hex     = "4e544c4d53535000020000000c000c003000000005028a000123456789abcdef0000000000000000300030003c00000053004500520056004500520002000c0053004500520056004500520001000c0053004500520056004500520007000800000000000000000000000000"
	fixtureType3Hex     = "4e544c4d5353500003000000180018005c0000007a007a007400000012001200400000000a000a0052000000000000005c00000000000000ee0000000502888057004f0052004b00470052004f005500500061006c00690063006500033dcb9976daffaa3021000edc9340dc316e7a784b594f51a4237774b92f78a14c527748d01c863201010000000000000000000000000000316e7a784b594f510000000002000c0053004500520056004500520001000c005300450052005600450052000700080000000000000000000900160063006900660073002f005300450052005600450052000000000000000000"
)

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

func fixtureChallenge(t *testing.T) [8]byte {
	t.Helper()
	var c [8]byte
	copy(c[:], mustHex(t, fixtureChallengeHex))
	return c
}

// TestMD4RFC1320Vectors checks the in-package MD4 against the published RFC 1320
// Appendix A.5 test suite, so the NT-hash foundation matches the spec rather than
// only itself.
func TestMD4RFC1320Vectors(t *testing.T) {
	cases := []struct{ in, want string }{
		{"", "31d6cfe0d16ae931b73c59d7e0c089c0"},
		{"a", "bde52cb31de33e46245e05fbdbd6fb24"},
		{"abc", "a448017aaf21d8525fc10ae87aa6729d"},
		{"message digest", "d9130a8164549fe818874806e1c7014b"},
		{"abcdefghijklmnopqrstuvwxyz", "d79e1c308aa5bbcdeea8ed63df412da9"},
		{"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", "043f8582f241db351ce627e153e7f0e4"},
		{"12345678901234567890123456789012345678901234567890123456789012345678901234567890", "e33b4ddc9c38f2199c3e7b164fcc0536"},
	}
	for _, c := range cases {
		got := md4Sum([]byte(c.in))
		if hex.EncodeToString(got[:]) != c.want {
			t.Errorf("MD4(%q) = %x, want %s", c.in, got, c.want)
		}
	}
}

// TestNTHash anchors the NT hash on two independent points: the universally
// known empty-password value and an impacket-computed value.
func TestNTHash(t *testing.T) {
	if got := NTHash(""); hex.EncodeToString(got[:]) != "31d6cfe0d16ae931b73c59d7e0c089c0" {
		t.Errorf("NTHash(\"\") = %x", got)
	}
	if got := NTHash("S3cret!"); hex.EncodeToString(got[:]) != fixtureNTHashHex {
		t.Errorf("NTHash(\"S3cret!\") = %x, want %s", got, fixtureNTHashHex)
	}
}

// TestNTOWFv2SpecVector checks NTOWFv2 against the worked example in MS-NLMP
// 4.2.4.1.1 (User / Domain / Password), exercising MD4, the UTF-16LE encoding,
// the user uppercasing and HMAC-MD5 composition against a spec-published value.
func TestNTOWFv2SpecVector(t *testing.T) {
	const want = "0c868a403bfd7a93a3001ef22ef02e3f"
	got := ntowfv2(NTHash("Password"), "User", utf16LE("Domain"))
	if hex.EncodeToString(got) != want {
		t.Errorf("NTOWFv2 = %x, want %s", got, want)
	}
	// The user name is uppercased before hashing (MS-NLMP 3.3.2): a lowercase
	// spelling must key the response identically, or NTLM logins would depend on
	// the exact case the client typed.
	if lower := ntowfv2(NTHash("Password"), "user", utf16LE("Domain")); !bytes.Equal(got, lower) {
		t.Error("NTOWFv2 must uppercase the user name before hashing")
	}
}

// TestBuildChallengeMatchesInteropLayout pins BuildChallenge to the exact bytes
// that impacket parsed and answered in the fixture, so the CHALLENGE this server
// emits is provably the one a real NTLM client consumes.
func TestBuildChallengeMatchesInteropLayout(t *testing.T) {
	got := BuildChallenge(fixtureChallenge(t), "SERVER", 0)
	want := mustHex(t, fixtureType2Hex)
	if !bytes.Equal(got, want) {
		t.Errorf("BuildChallenge mismatch:\n got %x\nwant %x", got, want)
	}
}

// TestParseAuthenticateExtractsFields confirms the type-3 parser follows the
// message's own offsets to recover the identity and response.
func TestParseAuthenticateExtractsFields(t *testing.T) {
	auth, err := ParseAuthenticate(mustHex(t, fixtureType3Hex))
	if err != nil {
		t.Fatalf("ParseAuthenticate: %v", err)
	}
	if auth.User != "alice" {
		t.Errorf("user = %q, want alice", auth.User)
	}
	if !bytes.Equal(auth.Domain, utf16LE("WORKGROUP")) {
		t.Errorf("domain = %x, want %x", auth.Domain, utf16LE("WORKGROUP"))
	}
	if len(auth.NTResponse) < 16 {
		t.Errorf("NtChallengeResponse too short: %d bytes", len(auth.NTResponse))
	}
}

// TestVerifyNTLMv2AcceptsValidResponse is the cross-implementation gate: the
// server verifies an NTLMv2 response produced independently by impacket.
func TestVerifyNTLMv2AcceptsValidResponse(t *testing.T) {
	auth, err := ParseAuthenticate(mustHex(t, fixtureType3Hex))
	if err != nil {
		t.Fatalf("ParseAuthenticate: %v", err)
	}
	var nt [16]byte
	copy(nt[:], mustHex(t, fixtureNTHashHex))
	if !VerifyNTLMv2(auth, fixtureChallenge(t), nt) {
		t.Error("VerifyNTLMv2 rejected a valid impacket-generated response")
	}
}

// TestVerifyNTLMv2RejectsWrongPassword proves verification actually depends on
// the password: the same response under a different NT hash must fail.
func TestVerifyNTLMv2RejectsWrongPassword(t *testing.T) {
	auth, err := ParseAuthenticate(mustHex(t, fixtureType3Hex))
	if err != nil {
		t.Fatalf("ParseAuthenticate: %v", err)
	}
	if VerifyNTLMv2(auth, fixtureChallenge(t), NTHash("not-the-password")) {
		t.Error("VerifyNTLMv2 accepted a response under the wrong NT hash")
	}
}

// TestVerifyNTLMv2RejectsWrongChallenge proves the response is bound to the
// server challenge that was issued: replaying it against another challenge fails.
func TestVerifyNTLMv2RejectsWrongChallenge(t *testing.T) {
	auth, err := ParseAuthenticate(mustHex(t, fixtureType3Hex))
	if err != nil {
		t.Fatalf("ParseAuthenticate: %v", err)
	}
	var nt [16]byte
	copy(nt[:], mustHex(t, fixtureNTHashHex))
	var wrong [8]byte // not the issued challenge
	if VerifyNTLMv2(auth, wrong, nt) {
		t.Error("VerifyNTLMv2 accepted a response bound to a different challenge")
	}
}

// TestParseNegotiate accepts a well-formed type-1 and rejects messages of the
// wrong type or signature.
func TestParseNegotiate(t *testing.T) {
	neg := append([]byte("NTLMSSP\x00"), 0x01, 0, 0, 0, 0x05, 0x82, 0x08, 0xe2)
	n, err := ParseNegotiate(neg)
	if err != nil {
		t.Fatalf("ParseNegotiate: %v", err)
	}
	if n.Flags != 0xe2088205 {
		t.Errorf("flags = %#x", n.Flags)
	}
	if _, err := ParseNegotiate(mustHex(t, fixtureType3Hex)); err == nil {
		t.Error("ParseNegotiate accepted a type-3 message")
	}
	if _, err := ParseNegotiate([]byte("not-ntlm")); err == nil {
		t.Error("ParseNegotiate accepted a non-NTLMSSP buffer")
	}
}

// TestParseAuthenticateRejectsMalformed guards the bounds checks: a truncated
// buffer and a wrong-type message must error rather than panic.
func TestParseAuthenticateRejectsMalformed(t *testing.T) {
	if _, err := ParseAuthenticate([]byte("NTLMSSP\x00")); err == nil {
		t.Error("accepted a truncated message")
	}
	if _, err := ParseAuthenticate(mustHex(t, fixtureType2Hex)); err == nil {
		t.Error("accepted a type-2 message as type-3")
	}
}
