#!/bin/bash
# uMailServer Installation Script
# Usage: curl -fsSL https://raw.githubusercontent.com/KilimcininKorOglu/uMailServer/main/scripts/install.sh | sudo bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Variables
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
DATA_DIR="${DATA_DIR:-/var/lib/umailserver}"
CONFIG_DIR="${CONFIG_DIR:-/etc/umailserver}"
LOG_DIR="${LOG_DIR:-/var/log/umailserver}"
RUN_DIR="${RUN_DIR:-/var/run/umailserver}"
USER="${USER:-umail}"
BINARY_NAME="umailserver"

# Architecture detection
ARCH=$(uname -m)
case $ARCH in
    x86_64)
        ARCH="amd64"
        ;;
    aarch64|arm64)
        ARCH="arm64"
        ;;
    *)
        echo -e "${RED}Unsupported architecture: $ARCH${NC}"
        exit 1
        ;;
esac

OS=$(uname -s | tr '[:upper:]' '[:lower:]')

# Functions
print_banner() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║                                                           ║"
    echo "║   uMailServer - One binary. Complete email.              ║"
    echo "║                                                           ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

check_dependencies() {
    local deps=("curl" "git" "systemctl" "go")
    for dep in "${deps[@]}"; do
        if ! command -v "$dep" &> /dev/null; then
            log_error "Required dependency not found: $dep"
            exit 1
        fi
    done
}

create_user() {
    if ! id "$USER" &>/dev/null; then
        log_info "Creating user: $USER"
        useradd -r -s /bin/false -d "$DATA_DIR" "$USER"
    else
        log_warn "User $USER already exists"
    fi
}

create_directories() {
    log_info "Creating directories..."
    mkdir -p "$DATA_DIR" "$CONFIG_DIR" "$LOG_DIR" "$RUN_DIR"
    chown "$USER:$USER" "$DATA_DIR" "$LOG_DIR" "$RUN_DIR"
    chmod 750 "$DATA_DIR"
    chmod 755 "$LOG_DIR" "$RUN_DIR"
}

download_binary() {
    log_info "Building uMailServer from source..."

    # Check for Go
    if ! command -v go &> /dev/null; then
        log_error "Go is not installed. Please install Go 1.25+ first:"
        log_error "  curl -fsSL https://go.dev/dl/go1.25.0.linux-amd64.tar.gz | tar -C /usr/local -xzf -"
        log_error "  echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile"
        exit 1
    fi

    # Clone or update repo
    local repo_dir="/tmp/umailserver-src"
    if [[ -d "$repo_dir" ]]; then
        log_info "Updating existing source..."
        cd "$repo_dir"
        git pull
    else
        log_info "Cloning repository..."
        git clone https://github.com/KilimcininKorOglu/uMailServer.git "$repo_dir"
        cd "$repo_dir"
    fi

    # Build
    log_info "Building for ${OS}/${ARCH}..."
    CGO_ENABLED=0 GOOS=linux GOARCH="${ARCH}" go build -ldflags "-s -w" -o "${INSTALL_DIR}/${BINARY_NAME}" ./cmd/umailserver

    chmod +x "${INSTALL_DIR}/${BINARY_NAME}"
    log_info "Binary installed to: ${INSTALL_DIR}/${BINARY_NAME}"
}

create_systemd_service() {
    log_info "Creating systemd service..."

    cat > /etc/systemd/system/umailserver.service << EOF
[Unit]
Description=uMailServer - One binary. Complete email.
Documentation=https://github.com/KilimcininKorOglu/uMailServer
After=network.target

[Service]
Type=simple
User=${USER}
Group=${USER}
ExecStart=${INSTALL_DIR}/${BINARY_NAME} serve --config=${CONFIG_DIR}/umailserver.yaml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=umailserver

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${DATA_DIR} ${LOG_DIR} ${RUN_DIR}

# Environment
Environment=HOME=${DATA_DIR}

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    log_info "Systemd service created"
}

generate_config() {
    if [[ ! -f "${CONFIG_DIR}/umailserver.yaml" ]]; then
        log_info "Generating default configuration..."

        local hostname="${HOSTNAME:-mail.example.com}"
        local domain="${DOMAIN:-example.com}"
        local admin_email="${ADMIN_EMAIL:-admin@example.com}"

        cat > "${CONFIG_DIR}/umailserver.yaml" << EOF
# uMailServer Configuration
# Generated by install.sh

server:
  hostname: ${hostname}
  data_dir: ${DATA_DIR}

tls:
  acme:
    enabled: true
    email: ${admin_email}
    challenge: http-01

smtp:
  inbound:
    enabled: true
    port: 25
    bind: "0.0.0.0"
  submission:
    enabled: true
    port: 587
    bind: "0.0.0.0"
    require_auth: true
    require_tls: true
  submission_tls:
    enabled: true
    port: 465
    bind: "0.0.0.0"
    require_auth: true

imap:
  enabled: true
  port: 993
  bind: "0.0.0.0"
  starttls_port: 143

pop3:
  enabled: true
  port: 995
  bind: "0.0.0.0"

managesieve:
  enabled: true
  port: 4190
  bind: "0.0.0.0"

http:
  enabled: true
  port: 443
  http_port: 80
  bind: "0.0.0.0"

admin:
  enabled: true
  bind: "127.0.0.1"
  port: 8443

security:
  jwt_secret: ""

metrics:
  enabled: true
  port: 8081
  bind: "127.0.0.1"

database:
  path: ${DATA_DIR}/umailserver.db

logging:
  level: info
  format: json
  output: stdout

domains: []

EOF

        chmod 600 "${CONFIG_DIR}/umailserver.yaml"
        chown "${USER}:${USER}" "${CONFIG_DIR}/umailserver.yaml"
        log_info "Configuration file created: ${CONFIG_DIR}/umailserver.yaml"
    else
        log_warn "Configuration file already exists"
    fi
}

open_ports() {
    log_info "Configuring firewall..."

    if command -v ufw &> /dev/null; then
        ufw allow 80/tcp    # ACME HTTP-01
        ufw allow 443/tcp   # HTTPS
        ufw allow 25/tcp    # SMTP inbound
        ufw allow 465/tcp   # SMTPS
        ufw allow 587/tcp   # SMTP submission
        ufw allow 143/tcp    # IMAP STARTTLS
        ufw allow 993/tcp    # IMAPS
        ufw allow 995/tcp    # POP3S
        ufw allow 4190/tcp   # ManageSieve
        ufw allow 8443/tcp   # Admin API
        log_info "UFW rules added"
    elif command -v firewall-cmd &> /dev/null; then
        firewall-cmd --permanent --add-port=80/tcp    # ACME HTTP-01
        firewall-cmd --permanent --add-port=443/tcp   # HTTPS
        firewall-cmd --permanent --add-port=25/tcp    # SMTP inbound
        firewall-cmd --permanent --add-port=465/tcp   # SMTPS
        firewall-cmd --permanent --add-port=587/tcp   # SMTP submission
        firewall-cmd --permanent --add-port=143/tcp   # IMAP STARTTLS
        firewall-cmd --permanent --add-port=993/tcp   # IMAPS
        firewall-cmd --permanent --add-port=995/tcp   # POP3S
        firewall-cmd --permanent --add-port=4190/tcp  # ManageSieve
        firewall-cmd --permanent --add-port=8443/tcp  # Admin API
        firewall-cmd --reload
        log_info "FirewallD rules added"
    else
        log_warn "No supported firewall found (ufw or firewalld)"
    fi
}

print_next_steps() {
    echo -e "${GREEN}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║                                                           ║"
    echo "║   uMailServer installed successfully!                    ║"
    echo "║                                                           ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. Edit configuration:"
    echo "     sudo nano ${CONFIG_DIR}/umailserver.yaml"
    echo ""
    echo "  2. Run quickstart to create your first account:"
    echo "     sudo umailserver quickstart admin@yourdomain.com"
    echo ""
    echo "  3. Start the server:"
    echo "     sudo systemctl enable --now umailserver"
    echo ""
    echo "  4. Check status:"
    echo "     sudo systemctl status umailserver"
    echo ""
    echo "  5. View logs:"
    echo "     sudo journalctl -u umailserver -f"
    echo ""
    echo "Documentation: https://docs.umailserver.com"
    echo "Support: https://github.com/umailserver/umailserver/issues"
    echo ""
}

# Main
main() {
    print_banner
    check_root
    check_dependencies

    log_info "Installing uMailServer ${VERSION} for ${OS}/${ARCH}..."

    create_user
    create_directories
    download_binary
    create_systemd_service
    generate_config
    open_ports

    print_next_steps
}

main "$@"
